[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 10000
via_ir = true
evm_version = "cancun"

[rpc_endpoints]
arc_testnet = "${ARC_TESTNET_RPC_URL}"

[etherscan]
arc_testnet = { key = "${ARC_EXPLORER_API_KEY}", url = "${ARC_EXPLORER_API_URL}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[fuzz]
runs = 512

[invariant]
runs = 256
depth = 64
